nohup: ignoring input
INFO    -  Building documentation...
INFO    -  MERMAID2  - Initialization arguments: {'securityLevel': 'loose'}
INFO    -  MERMAID2  - Using javascript library (10.4.0):
   https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
INFO    -  [macros] - No default module `main` found
INFO    -  [macros] - Config variables: ['extra', 'config', 'environment', 'plugin', 'git', 'consent', 'social', 'generator', 'macros', 'filters', 'filters_builtin']
INFO    -  [macros] - Config macros: ['context', 'macros_info', 'now', 'fix_url']
INFO    -  [macros] - Config filters: ['pretty', 'relative_url']
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
INFO    -  Doc file 'app/overview.md' contains a link '#supported-versions--lifecycle', but there is no such anchor on this page.
INFO    -  Doc file 'app/configuration/entrypoint-cli.md' contains a link '#cli-commands--flags-used', but there is no such anchor on this page.
INFO    -  Doc file 'app/configuration/files-and-paths.md' contains a link '#data-directories--volumes', but there is no such anchor on this page.
INFO    -  Doc file 'app/configuration/files-and-paths.md' contains a link '#certificates--secrets', but there is no such anchor on this page.
INFO    -  Doc file 'domain/bounded-contexts.md' contains a link '#shared-kernel--acl', but there is no such anchor on this page.
INFO    -  Doc file 'ops/networking.md' contains a link '#proxy--load-balancer', but there is no such anchor on this page.
INFO    -  Doc file 'ops/networking.md' contains a link '#tls--security', but there is no such anchor on this page.
INFO    -  Doc file 'ops/runbook.md' contains a link '#health--readiness', but there is no such anchor on this page.
INFO    -  Doc file 'ops/upgrades-rollback.md' contains a link '#validation--testing', but there is no such anchor on this page.
INFO    -  Documentation built in 0.89 seconds
Traceback (most recent call last):
  File "/home/runner/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/lib/python3.10/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 272, in serve_command
    serve.serve(**kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 104, in serve
    server.serve(open_in_browser=open_in_browser)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/livereload/__init__.py", line 173, in serve
    self.server_bind()
  File "/usr/lib/python3.10/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
